### PR TITLE
Support changing database information

### PR DESCRIPTION
**Pull request by WatanabeToshimitsu**
## What?
- Support changing database information

## Why?
- Change database info by Web GUI

## See also
Resolves https://github.com/dataware-tools/dataware-tools/issues/6

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/76#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by WatanabeToshimitsu** [comment]
@yusukefs 
実装終わりました！レビューお願いして大丈夫でしょうか！

**Comment by yusukefs** [comment]
実装あざます！ほぼいい感じなのですが、以下の2点が気になりました

1. 情報更新するモーダルを開いた時に、フォームに現在の情報を初期値として入れたほうが分かりやすい＆更新しやすいと思いましたがどうでしょう？
2. 他のモーダルと同様に、モーダル外をクリックしたときにモーダルが閉じるようにしたほうが良さそう

**Comment by yusukefs** [comment]
コード見る限り初期値が入るはずなんですがなぜか [currentData](https://github.com/dataware-tools/app-data-browser-next/pull/76/files#diff-675abed8246ec175212937988fa17b708ccac7a1e12676356672bcaf334a87eeR167) が undefined になってるみたいです
おそらくわたなべくんの環境だと初期値が入りますかね？

**Comment by yusukefs** [comment]
あっすみませんよく見たら親からcurrentData渡してなかったですね
いずれ実装できるようにしてある感じでしょうか

**Review by yusukefs — APPROVED** [review]
とてもいい感じです！LGTM

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/76#" title="Author self-approved">WatanabeToshimitsu</a>*, *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/76#pullrequestreview-711277245" title="Approved">yusukefs</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu,yusukefs]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by hdl-service** [comment]
New changes are detected. LGTM label has been removed.

**Comment by WatanabeToshimitsu** [comment]
@yusukefs 
master にマージしたら結構変更が生まれたので，申し訳ないんですがもう一度触ってもらうことだけ可能でしょうか？
一応僕の方でも動作確認はしたんですが，念のため....

**Comment by yusukefs** [comment]
動作確認OKでした！

**Comment by yusukefs** [comment]
LGTM

**Review by yusukefs — APPROVED** [review]
LGTM

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/76#" title="Author self-approved">WatanabeToshimitsu</a>*, *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/76#pullrequestreview-711291541" title="Approved">yusukefs</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu,yusukefs]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
