### PR TITLE
Show formatted record info

### PR DESCRIPTION
**Pull request by WatanabeToshimitsu**
## What?
- Show formatted record info

## Why?
- For easy viewing record detail

## See also
- Resolves https://github.com/dataware-tools/dataware-tools/issues/53

## Screenshot or video
ToggleHowToShowRecordDetail

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/117#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by d-hayashi** [comment]
慣れている人にはこちらの表示の方が良いかと思いますが、そうでない人にとっては今までのリスト形式の表示の方が見やすいのでは (ネストしてる部分を除く) と思うのですが、どう思います？
今までの表示の仕方 + 画面のどこかにトグルを用意してトグルをONにしたらJSON形式で見れるみたいな方法もアリかなと思ったり。。

**Comment by WatanabeToshimitsu** [comment]
> 慣れている人にはこちらの表示の方が良いかと思いますが、そうでない人にとっては今までのリスト形式の表示の方が見やすいのでは (ネストしてる部分を除く) と思うのですが、どう思います？
> 今までの表示の仕方 + 画面のどこかにトグルを用意してトグルをONにしたらJSON形式で見れるみたいな方法もアリかなと思ったり。。

対応してみました！ どうでしょうか？

**Comment by d-hayashi** [comment]
爆速
いい感じですね！

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/117#issuecomment-891671938" title="LGTM">d-hayashi</a>*, *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/117#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu,d-hayashi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by hdl-service** [comment]
New changes are detected. LGTM label has been removed.

**Pull request merged**
