### PR TITLE
Fix bug that too long content have unexpected appearance

### PR DESCRIPTION
**Pull request by WatanabeToshimitsu**
## What?
- Fix bug that too long content have unexpected appearance

## Why?
- bug fix

## See also
- Resolves https://github.com/dataware-tools/dataware-tools/issues/43

## Screenshot or video
FixTooLongComponentBug

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/86#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by d-hayashi** [comment]
これってどう表示されるのが理想なんでしたっけ？
文字列によっては `overflow-wrap: break-word` とかで改行したほうが読みやすいこともあるのでは？と思いました

**Comment by d-hayashi** [comment]
あと、`INFO` と `FILES` タブでモーダルの大きさが変わると若干使いづらいかも？と思いました

https://user-images.githubusercontent.com/24401842/126249390-5d32f693-4ba7-447b-92e8-34dd5f65a29e.mov

**Comment by WatanabeToshimitsu** [comment]
文字の折り返しについては少し試してみます！
モーダルのサイズが変わる問題についても，少し案があるので試してみます

**Comment by WatanabeToshimitsu** [comment]
@d-hayashi 
理想的な形にはできなかったんですが，とりあえず「サイズを固定する」というのと「長い文字を折り返す」というのをやってみました どうでしょうか？
FixRecordDetailModalSize

**Comment by d-hayashi** [comment]
爆速！
いい感じだと思います！

**Review by d-hayashi — APPROVED** [review]
LGTM!

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/86#pullrequestreview-710257657" title="Approved">d-hayashi</a>*, *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/86#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu,d-hayashi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
