### PR TITLE
Support changing order of input/display fields by drag and drop

### PR DESCRIPTION
**Pull request by WatanabeToshimitsu**
## What?
- Support changing order of input/display fields by drag and drop

## Why?
- Make it easy

## See also
- https://github.com/dataware-tools/dataware-tools/issues/20
- https://github.com/dataware-tools/dataware-tools/issues/17

## Screenshot or video
DraggableConfig

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/67#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yusukefs** [comment]
ドロップダウンのところでもドラッグアンドドロップできるので↓の挙動になってしまうのが気になりました
https://user-images.githubusercontent.com/13210107/124862710-d4c8b300-dff0-11eb-89c7-ed0c9dbce179.mov

左のハンドルの部分とラベルだけDNDできるようにするのはどうでしょうか？

**Comment by WatanabeToshimitsu** [comment]
意外とサクッとできました！

**Comment by yusukefs** [comment]
おーいい感じです！あざます！

**Review by yusukefs — APPROVED** [review]
LGTM

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/67#" title="Author self-approved">WatanabeToshimitsu</a>*, *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/67#pullrequestreview-701764927" title="Approved">yusukefs</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu,yusukefs]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
