### PR TITLE
Bump react-router-dom

### PR DESCRIPTION
**Pull request by WatanabeToshimitsu**
## What?
Bump react-router-dom

## Why?
メジャーバージョンのアップデートでAPIが変わったので

## See also
https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v6

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/311#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by WatanabeToshimitsu** [comment]
@d-hayashi 
リマインド！

**Comment by d-hayashi** [comment]
Bump系ってどこまでチェックすれば良いですかね？

**Comment by WatanabeToshimitsu** [comment]
@d-hayashi 
諸々こっちの方でもチェックしつつやってるので，基本的に軽くレビューしてもらえばいいんですが，一番見て欲しいのは動作面です！
というのも，Bump 系の PR は，メジャーバージョンの更新によって使い方が変わったり，影響範囲が大きい感じの更新を行ったりしたときにレビューをお願いしていることが多いはずなので，動作的なデグレがあり得るからです

これでいうと，ページが遷移するかとか，その時に履歴が溜まってるかとか，そういうのを確認していただけると嬉しいです

理想的には，ドキュメントとか release note/CHANGELOG を見て差分に従えてるかも見てもらえるのが一番なんですが，これはある程度そのライブラリに慣れてないと相当きついと思うので，興味があればで大丈夫です

**Review by d-hayashi — APPROVED** [review]
LGTM!

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/311#pullrequestreview-846457545" title="Approved">d-hayashi</a>*, *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/311#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu,d-hayashi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
